# Generated by Django 5.1.6 on 2025-02-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rank', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('type', models.CharField(choices=[('gold', 'Gold'), ('water', 'Water'), ('air', 'Air'), ('universal', 'Universal')], max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
