# Generated by Django 5.1.6 on 2025-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anymix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
