# Generated by Django 5.1.6 on 2025-02-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anymix', '0002_alter_gen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen',
            name='rank',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]),
        ),
    ]
