# Generated by Django 4.2.19 on 2025-02-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anymix', '0005_rename_father_only_gen_mother_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gen',
            old_name='mother_only',
            new_name='father_only',
        ),
    ]
